### ISSUE TITLE
crash with mod

### ISSUE THREAD

**Issue by TheVirusNVGM** [Ultreon/ERROR422#2]
[crash-2024-01-16_02.53.03-fml.txt](https://github.com/Ultreon/ERROR422/files/13943871/crash-2024-01-16_02.53.03-fml.txt)

**Comment by XyperCode** [comment]
How did mixins broke on Forge :skull:

**Comment by TheVirusNVGM** [comment]
Another question: will the mod support multiplayer later? I would like to survive like this with the same friend and so on

**Comment by XyperCode** [comment]
That was my intention to do at some point.

**Comment by XyperCode** [comment]
Fixed in https://github.com/Ultreon/ERROR422/commit/7a79a3474f772263ff8e19734c7d1672f0feef64
