### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by YaBoiCameronYT** [Ultreon/ERROR422#9]
The game crashes every time I try to load the mod. I installed all the dependencies and tried it on forge and fabric and it crashes. Tried different launchers, still crashes. What am I doing wrong?

**Comment by XyperCode** [comment]
Crash report file? :eyes:

**Comment by YaBoiCameronYT** [comment]
[crash-2024-06-29_13.20.56-fml.txt](https://github.com/user-attachments/files/16042175/crash-2024-06-29_13.20.56-fml.txt)

**Comment by YaBoiCameronYT** [comment]
[crash-2024-06-29_13.19.42-fml.txt](https://github.com/user-attachments/files/16042181/crash-2024-06-29_13.19.42-fml.txt)

**Comment by XyperCode** [comment]
You didn't install Architectury which is a dependency of UltreonLib...
